name: Tasks
on:
 schedule:
   - cron: '0 */8 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: filters-build
      uses: minoplhy/filters-build_actions@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
    - name: build
      uses: minoplhy/filters-maker@v1.1.0
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        Destination_UNAME: "minoplhy"
        Destination_REPO: "filters"
        Destination_VERSION: "ucate"
        ACTION_FILE: "action.py"
        GIT_NAME: "HurBar"
        GIT_EMAIL: "hubr@3qx.nl"
        REPO_BRANCH: "main"
        sub_action_location: "sub-action.py"
  restart_when_failed:
    name: Dispatches run when it failed
    runs-on: ubuntu-latest
    if: failure()
    needs: [build]
    steps:
    - name: Re-Run the workflow
      run: |
        curl -i \
        -X POST \
        -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: token ${{ secrets.API_TOKEN_GITHUB }}" \
        https://api.github.com/repos/minoplhy/filters/actions/workflows/11794283/dispatches \
        -d '{"ref": "${{ github.ref }}" }'
