name: Tasks
on:
  schedule:
   - cron: '0 */12 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: build
      uses: minoplhy/filters-maker@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        Destination_NAME: "filters"
        Destination_UNAME: "minoplhy"
        Destination_REPO: "filters"
        Destination_FOLDER: "Private-build"
        Destination_VERSION: "ucate"
        ACTION_FILE: "action.py"
        GIT_NAME: "HurBar"
        GIT_EMAIL: "Hurbar@m21.kylz.nl"
        REPO_BRANCH: "master"
        BRANCH_VERSION: "main"
    - name: mass name changes
      uses: minoplhy/mass-name-change@main
      env:
         API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        action_location: sub-action.py
        Repo: minoplhy/filters
    - name: "Makeup Releases"
      run: |
        echo "done!"

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "FILTERS"
          files: |
            /gh-releases/*
