name: Tasks
on:
  push:
  schedule:
   - cron: '* */12 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: build
      uses: minoplhy/filters-maker@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        Destination_NAME: "filters"
        Destination_UNAME: "minoplhy"
        Destination_REPO: "filters"
        Destination_VERSION: "Private-Build"
        GIT_NAME: "HurBar"
        GIT_EMAIL: "Hurbar@m21.kylz.nl"
        REPO_BRANCH: "main"
    - name: Checkout
      uses: actions/checkout@v2
