name: Tasks
on:
  schedule:
   - cron: '0 */4 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: filters-build
      uses: minoplhy/filters-build_actions@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
    - name: build
      uses: minoplhy/filters-maker@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        Destination_NAME: "filters"
        Destination_UNAME: "minoplhy"
        Destination_REPO: "filters"
        Destination_FOLDER: "Private-build"
        Destination_VERSION: "ucate"
        ACTION_FILE: "action.py"
        GIT_NAME: "HurBar"
        GIT_EMAIL: "hurbar@aspoblourib.1w1.one"
        REPO_BRANCH: "master"
        BRANCH_VERSION: "main"
        sub_action_location: "sub-action.py"
        sub_action_Repo: "minoplhy/filters"
  restart_when_failed:
    name: Re-Run the scheduled run when it failed
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule' && failure()
    needs: [build]
    steps:
    - name: Re-Run the workflow
      run: |
        curl -i \
        -X POST \
        -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: token ${{ secrets.API_TOKEN_GITHUB }}" \
        https://api.github.com/repos/minoplhy/filters/actions/runs/$GITHUB_RUN_ID/rerun \
        -d '{"ref": "${{ github.ref }}" }'
